[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
marketplace = "H8Tka4gybGNxtD9PZB7Y33F5bLW6kbFcZasvFYhdbwgZ"
minter = "DsWXjMnJ5b8gh5tKTRC5vJ8WKz2Eqdj7uPHq1Lq76DTm"
publishing_platform = "CLZfecSgY5BCfGAHLv46bGvqbbxEevkHxsFMRhV25wUF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
